services:
  adonis_app:
    container_name: adonis_app
    restart: always
    build:
      context: .
      target: base
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    env_file:
      - .env
    volumes:
      - ./:/home/node/app
    environment:
      - CHOKIDAR_USEPOLLING=1
      - CHOKIDAR_INTERVAL=2000
    command: dumb-init npm run dev

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - campus-connect-dados:/var/lib/postgresql/data

volumes:
  campus-connect-dados:
